### ISSUE TITLE
Plugin provided an invalid property of "default"

### ISSUE THREAD

**Issue by mandx** [getsentry/babel-gettext-extractor#4]
Using `babel-core@6.22.1`, `webpack@2.2.1`, `Node.js@v7.5.0` and this `.babelrc` file:
```json
{
  "presets": [
    ["latest", {
      "es2015": {
        "modules": false
      }
    }],
    "stage-3",
    "react"
  ],
  "plugins": [
    "babel-plugin-transform-class-properties",
    "babel-plugin-transform-runtime",
    "babel-gettext-extractor",
    "./bin/babel-relay-schema-plugin"
  ]
}
```

After a quick googling, I went into my local `node_modules/babel-gettext-extractor` and changed [this line](https://github.com/getsentry/babel-gettext-extractor/blob/18cbf641caf7e9349df8a07b83b70e0252ad3cd7/index.js#L35) from:

```javascript
exports.default = function() {
```

to:

```
module.exports = function() {
```

And then it worked perfectly.

Is there a Babel config option I'm missing?

**Comment by mandx** [comment]
Full stacktrace:
```
ERROR in ./src/index.js
Module build failed: Error: Plugin 2 specified in "/project/path/.babelrc" provided an invalid property of "default"
    at Plugin.init (/project/path/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/project/path/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /project/path/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/project/path/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/project/path/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:36)
    at OptionManager.init (/project/path/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/project/path/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/project/path/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/project/path/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/project/path/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/project/path/node_modules/babel-loader/lib/index.js:133:12)
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server babel-polyfill ./index.js

```

**Comment by colinwren** [comment]
I have ran into the exact same problem. @mandx your fix worked for me, thanks!

**Comment by mandx** [comment]
@colinwren Well is not really a fix, is more like a workaround to get it working locally. This is still a problem since the "fix" is not available in new installations.
